In [1]:
import os
import pandas as pd
import numpy as np

In [7]:
delimiter = "|"

lda_loadings_df = pd.read_csv("../data/output/LDA_LOADINGS.csv", index_col=0)
lda_top_words_df = pd.read_csv("../data/output/LDA_TOP_WORDS.csv")

print("Phi matrix shape:", lda_loadings_df.shape)
lda_loadings_df.head()

Phi matrix shape: (5, 2360)

,aaron,aaron's,abhor,abhorred,abiathar,abide,abideth,abigail,abijah,abimelech,...,zadok,zeal,zebulun,zechariah,zedekiah,zerah,zerubbabel,zeruiah,zidon,zion
T00,0.203208,15.429950,0.502559,719.806968,0.205180,0.201425,0.202863,28.854017,0.201644,0.201865,...,1.018650,1.197981,0.200012,1.199954,0.200017,1.199888,1.195483,0.200019,0.200003,0.201492
T01,106.192231,29.964297,3639.728159,0.306025,0.201976,3.289216,63.572291,17.830357,0.201407,0.201557,...,0.209658,0.201961,0.200012,0.200007,0.200019,0.200020,0.204444,0.203770,0.200003,3.227921
T02,0.201841,0.203788,0.214953,0.202322,0.201043,361.106144,0.220193,0.202191,0.201217,25.195446,...,0.200031,0.200018,0.200017,0.200016,0.200025,0.200028,0.200022,0.200023,0.201592,4.167626
T03,0.201546,0.200858,0.202327,0.483184,0.395145,0.201616,49.549126,0.203777,1967.194234,0.200626,...,0.371625,0.200021,1.199939,0.200012,1.192403,0.200032,0.200026,0.201457,0.200007,0.200259
T04,0.201173,0.201107,2.352002,0.201502,226.996655,0.201600,110.455527,7.909657,0.201498,0.200506,...,0.200036,0.200020,0.200019,0.200012,0.207537,0.200032,0.200025,4.194731,1.198394,0.202701

In [3]:
phi = lda_loadings_df.div(lda_loadings_df.sum(axis=1), axis=0)

phi.head()

,aaron,aaron's,abhor,abhorred,abiathar,abide,abideth,abigail,abijah,abimelech,...,zadok,zeal,zebulun,zechariah,zedekiah,zerah,zerubbabel,zeruiah,zidon,zion
T00,0.000010,0.000747,0.000024,0.034847,0.000010,0.000010,0.000010,0.001397,0.000010,0.000010,...,0.000049,0.000058,0.000010,0.000058,0.000010,0.000058,0.000058,0.000010,0.000010,0.000010
T01,0.005092,0.001437,0.174534,0.000015,0.000010,0.000158,0.003048,0.000855,0.000010,0.000010,...,0.000010,0.000010,0.000010,0.000010,0.000010,0.000010,0.000010,0.000010,0.000010,0.000155
T02,0.000014,0.000014,0.000014,0.000014,0.000013,0.024235,0.000015,0.000014,0.000014,0.001691,...,0.000013,0.000013,0.000013,0.000013,0.000013,0.000013,0.000013,0.000013,0.000014,0.000280
T03,0.000016,0.000016,0.000016,0.000038,0.000031,0.000016,0.003848,0.000016,0.152788,0.000016,...,0.000029,0.000016,0.000093,0.000016,0.000093,0.000016,0.000016,0.000016,0.000016,0.000016
T04,0.000016,0.000016,0.000182,0.000016,0.017558,0.000016,0.008544,0.000612,0.000016,0.000016,...,0.000015,0.000015,0.000015,0.000015,0.000016,0.000015,0.000015,0.000324,0.000093,0.000016

In [4]:
phi.sum(axis=1)

T00    1.0
T01    1.0
T02    1.0
T03    1.0
T04    1.0
dtype: float64

In [5]:
n_top = 10

phi_top_words = {}

for topic in phi.index:
    top_terms = (
        phi.loc[topic]
        .sort_values(ascending=False)
        .head(n_top)
    )
    phi_top_words[topic] = top_terms

phi_top_words

{'T00': abode           0.433301
 afraid          0.089281
 accord          0.051106
 abhorred        0.034847
 abominations    0.030119
 ahab            0.023925
 accomplished    0.015517
 arose           0.011919
 bear            0.009254
 almighty        0.008064
 Name: T00, dtype: float64,
 'T01': abhor        0.174534
 according    0.125077
 adam         0.111074
 camp         0.089103
 age          0.046325
 abound       0.040901
 account      0.019186
 anguish      0.016042
 answer       0.013485
 abner        0.011033
 Name: T01, dtype: float64,
 'T02': accomplished    0.240499
 abram           0.067302
 adultery        0.052562
 abraham's       0.046550
 adversaries     0.031220
 abide           0.024235
 abound          0.023291
 camp            0.016437
 lewdness        0.016321
 believed        0.014003
 Name: T02, dtype: float64,
 'T03': abijah       0.152788
 abraham      0.065023
 ah           0.039216
 arm          0.035097
 chaldeans    0.030228
 ahimaaz      0.028286
 beneath      0.025378
 amnon        0.025091
 corners      0.024791
 abound       0.022695
 Name: T03, dtype: float64,
 'T04': gomorrah       0.062745
 abomination    0.041552
 bondage        0.041458
 baskets        0.040946
 abner          0.033495
 acknowledge    0.032420
 afflict        0.030604
 astray         0.025076
 begotten       0.024440
 camp           0.022733
 Name: T04, dtype: float64}

In [6]:
delimiter = "|"
print("Delimiter:", delimiter)

Delimiter: |

In [8]:
os.makedirs("../data/output", exist_ok=True)

phi.to_csv("../data/output/LDA_PHI_PROBABILITIES.csv")

print("LDA phi probabilities saved.")

LDA phi probabilities saved.