In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
bow_sent = pd.read_csv("../data/output/BOW_SENT.csv", sep="|")

print("BOW_SENT shape:", bow_sent.shape)
bow_sent.head()

BOW_SENT shape: (616248, 17)

,book_number,chapter,verse,term_str,n,idf,tfidf,anger,anticipation,disgust,fear,joy,sadness,surprise,trust,positive,negative
0,1,1,1,and,1,0.264775,0.264775,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,1,1,beginning,1,5.700637,5.700637,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1,1,1,created,1,6.707441,6.707441,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1,1,1,earth,1,3.535988,3.535988,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1,1,1,god,1,2.082210,2.082210,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0

In [3]:
emo_cols = [
    "anger", "anticipation", "disgust", "fear",
    "joy", "sadness", "surprise", "trust",
    "positive", "negative"
]

In [4]:
doc_sent = (
    bow_sent
    .groupby(["book_number", "chapter", "verse"])[emo_cols]
    .sum()
    .reset_index()
)

doc_sent.head()

,book_number,chapter,verse,anger,anticipation,disgust,fear,joy,sadness,surprise,trust,positive,negative
0,1,1,1,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0
1,1,1,2,1.0,1.0,0.0,2.0,1.0,1.0,0.0,1.0,2.0,1.0
2,1,1,3,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0
3,1,1,4,1.0,3.0,0.0,3.0,3.0,1.0,1.0,3.0,3.0,1.0
4,1,1,5,1.0,1.0,0.0,2.0,1.0,1.0,0.0,1.0,1.0,1.0

In [5]:
bow = pd.read_csv("../data/output/BOW.csv", sep="|")

verse_lengths = (
    bow
    .groupby(["book_number", "chapter", "verse"])["n"]
    .sum()
    .reset_index(name="token_count")
)

doc_sent = doc_sent.merge(
    verse_lengths,
    on=["book_number", "chapter", "verse"],
    how="left"
)

for col in emo_cols:
    doc_sent[col] = doc_sent[col] / doc_sent["token_count"]

doc_sent.head()

,book_number,chapter,verse,anger,anticipation,disgust,fear,joy,sadness,surprise,trust,positive,negative,token_count
0,1,1,1,0.000000,0.100000,0.0,0.100000,0.100000,0.000000,0.000000,0.100000,0.100000,0.000000,10
1,1,1,2,0.034483,0.034483,0.0,0.068966,0.034483,0.034483,0.000000,0.034483,0.068966,0.034483,29
2,1,1,3,0.000000,0.090909,0.0,0.090909,0.090909,0.000000,0.000000,0.090909,0.090909,0.000000,11
3,1,1,4,0.058824,0.176471,0.0,0.176471,0.176471,0.058824,0.058824,0.176471,0.176471,0.058824,17
4,1,1,5,0.045455,0.045455,0.0,0.090909,0.045455,0.045455,0.000000,0.045455,0.045455,0.045455,22

In [8]:
delimiter = "|"
ohco_bag = ["book_number", "chapter", "verse"]

print("Delimiter used:", f'"{delimiter}"')
print("Document bag expressed in OHCO levels:", ohco_bag)

Delimiter used: "|"
Document bag expressed in OHCO levels: ['book_number', 'chapter', 'verse']

In [7]:
output_path = "../data/output/DOC_SENT.csv"

doc_sent.to_csv(
    output_path,
    sep="|",
    index=False
)

print("Saved:", output_path)

Saved: ../data/output/DOC_SENT.csv